### ISSUE TITLE
Stromwerte von Smartmeter um Faktor 10 zu groß

### ISSUE THREAD

**Issue by RoHa78** [daolis/ioBroker.sun2000-modbus#14]
Hi @daolis,
habe den Adapter mittlerweile ein paar Tage laufen und bis jetzt noch keine Ausfälle beobachten können. Was mir allerdings aufgefallen ist, dass die Stromwerte vom Smartmeter um den Faktor 10 zu hoch sind.

Habe dazu folgendes Beispiel, etwa zur gleichen Zeit gescreenshotted ;)
![Adapter IOBroker](https://github.com/daolis/ioBroker.sun2000-modbus/assets/54179753/8edc835b-d4fb-4b76-8651-b68fbc3103fa)

und hier die Werte von FusionSolar:
![FusionSolar](https://github.com/daolis/ioBroker.sun2000-modbus/assets/54179753/94bf4df5-5038-4eae-a017-21c1db29f7f6)

Denke da ist nur ein Faktor irgendwo falsch verrechnet.

Viele Grüße und nochmals vielen Dank für die tolle Arbeit!

**Comment by daolis** [comment]
Yep, wenn man den gain richtig einträgt, dann sollte es auch richtige Werte liefern.. 

https://github.com/daolis/ioBroker.sun2000-modbus/blob/main/src/lib/states.ts#L203
(Gain 10)
vs.
![image](https://github.com/daolis/ioBroker.sun2000-modbus/assets/2550938/1f8372eb-b94d-4926-8ef4-de0261c5bdc7)
