### ISSUE TITLE
Einheiten der Watt-Werte teilweise noch falsch

### ISSUE THREAD

**Issue by RoHa78** [daolis/ioBroker.sun2000-modbus#16]
**Describe the bug**  
Umstellung der Werte von KW in Watt sind zwar erfolgt, jedoch sind die Einheitenbezeichner noch in KW (oder ich habe seit Kurzem einen tollen Ertrag ;))

**To Reproduce**  
siehe Werte in IOBroker in den Datenpunkten

**Screenshots & Logfiles**  
![Einheiten](https://github.com/daolis/ioBroker.sun2000-modbus/assets/54179753/740aed60-9f43-4200-8e2a-d0fb358f6217)

**Versions:**  
aktuelle Testversion

**Comment by daolis** [comment]
Die States werde zwar erstellt (initial) aber anscheinend nicht upgedated...
Wenn du den State löscht, dann den adapter neu startest, dann sollte es passen.

Aber wie ich sehe hast du für den State schon was konfiguriert. Ich nehme mal an ein speichern in einer DB. Das wäre dann weg und du müsstest es neu konfigurieren...
Oder du stellst es per Hand um: `Edit` -> `Common` -> `Unit`

**Comment by RoHa78** [comment]
Dachte die States werden auch automatisch umgestellt. Habe es mal von "Hand" umgestellt, Danke für den Tip.
Seltsam dass bei dem Update dies nicht automatisch aktualisiert wird 🤔

**Comment by daolis** [comment]
@RoHa78 Sollte jetzt funktionieren...

**Comment by RoHa78** [comment]
Habe die aktuelle Version drüber installiert, die Einheiten sind nun korrekt, tolle Arbeit 😀
Schließe somit diesen Issue!
