### ISSUE TITLE
Object of state "sun2000-modbus.0.totalPowerUse" is missing the required property "common.type

### ISSUE THREAD

**Issue by sansonifabio** [daolis/ioBroker.sun2000-modbus#18]
**Describe the bug**  
Hier eine kleine Warnung:

`sun2000-modbus.0 | 2023-10-04 15:40:10.290 | warn | Object of state "sun2000-modbus.0.totalPowerUse" is missing the required property "common.type"`

**Versions:**  
 - Adapter version: 0.0.1
 - JS-Controller version: 5.0.12
 - Node version: v18.18.0
 - Operating system: Debian Bookworm

Herzliche Grüße
Fabio

**Comment by daolis** [comment]
Pro Tip für das nächste mal (an mich): Wenn ich etwas ändere, dann hilft pushen ungemein! :see_no_evil:

**Comment by sansonifabio** [comment]
Danke Fehler ist weg
