### ISSUE TITLE
Minor/cosmetic issue: SoC translated incorrectly to "state of capacity" (correct: "state of charge")

### ISSUE THREAD

**Issue by madmat17** [daolis/ioBroker.sun2000-modbus#26]
First of all: A VERY promising and cool adapter for ioBroker!
Keep on rocking!

**Describe the bug**  
You translated the register 37760 to "stateOfCapacity", whereas this register is holding the current state of charge.
Register 37760 should be translated to "stateOfCharge".

**Versions:**  
 - Adapter version: 0.0.1

**Additional context**  
The state of capacity would more describe the remaining total capacity compared to the battery's initial capacity (the battery health as known from mobile phones) but that value doesn't seem to be held in an externally accessible register. To my knowledge that value isn't transparent to the user, since the gross capacity and net capacity derive from each other and Huawei / LG already added some "reserves" to cover the wearing of the battery.

**Comment by daolis** [comment]
Thanks for reporting it.
The bad think is...
This is more ore less a breaking change... If i change this value, the historical values are stored in ...Capacity, and the noew ones in ...Charge.

**Comment by madmat17** [comment]
I know that this might be quite cumbersome, but one option could be to have a translation table for the data object names which the user can configure.
For instance having the adapter writing the discharge power of the battery to the object "dischargePower" per default (like it is right now), but the user could change that one to "Entladeleistung", "ontladingskracht", or "kisütési teljesítmény", ... or whatever object name in ioBroker is convenient for the user.

That would also enable users to maintain their existing database entries (like InfluxDB) in case they already have existing ones with different namings without setting up aliases in ioBroker.

Alternatively the users might set up aliases directly in ioBroker and have them being written to a database (I'm not that firm with ioBroker yet to confirm, whether that'd be working).

**Comment by daolis** [comment]
Already implemented. Will come in next release.
