### ISSUE TITLE
not all stringdata are displayed

### ISSUE THREAD

**Issue by micklafisch** [daolis/ioBroker.sun2000-modbus#29]
**Describe the bug**  
Only data from string 1 and 2 are displayed with "pvXcurrent" and "pvXvoltage", but mine has in sum 4 strings

**Expected behavior**  
show the data from all strings

**Screenshots & Logfiles**  
adapter:
![image](https://github.com/daolis/ioBroker.sun2000-modbus/assets/44931749/3950c59e-d5e0-44b6-84af-f16291a195e4)

my nodered:
![image](https://github.com/daolis/ioBroker.sun2000-modbus/assets/44931749/dab78ed0-e47f-4eb0-b421-6f6f1c61d078)

**Comment by daolis** [comment]
Suggestion:
We could use the Register 30071 (Number of PV strings) to dynamically create the correct number of PVn-Voltage/Current states

**Comment by daolis** [comment]
Impl in progress. Will come in next release.

**Comment by daolis** [comment]
Dynamicall added number oof registers depending on Number of PV strings. Same for MPPTrackers!
