### ISSUE TITLE
No data for ChargePower and CurrentDayChargeCapacity

### ISSUE THREAD

**Issue by Thomas-FHU** [daolis/ioBroker.sun2000-modbus#32]
I'm running version 0.0.2 in iobroker 6.13.15 on Ubuntu 22.04.
SDongleA-05 has firmware V100R001C00SPC133 attached to a SUN2000-8KTL-M1.
Battery is a LUNA2000 with 10kWh capacity, firmware V100R002C00SPC119.

All data obtained by the adapter seem to be correct, except for ChargePower and CurrentDayChargeCapacity which always display 0 kW(h).

Anybody else with this problem?

**Comment by daolis** [comment]
Added it. Will come in next release.

**Comment by daolis** [comment]
Released version 0.1.0
