### ISSUE TITLE
Weitere Register abfragen

### ISSUE THREAD

**Issue by Basti-RX** [daolis/ioBroker.sun2000-modbus#34]
Hallo,
wäre es möglich weitere Register abzufragen?
Folgende Register wären aus meiner Sicht zur auswerten noch gut.

![Screenshot 2024-02-07 at 19-32-06 Modbus Interface Definitions (V3 0) - Solar Inverter Modbus Interface Definitions (V3 0) pdf](https://github.com/daolis/ioBroker.sun2000-modbus/assets/24960835/1342a245-610a-4fe1-b64e-e8902bc3a31e)
![Screenshot 2024-02-07 at 19-33-15 Modbus Interface Definitions (V3 0) - Solar Inverter Modbus Interface Definitions (V3 0) pdf](https://github.com/daolis/ioBroker.sun2000-modbus/assets/24960835/00a2d8a7-534f-478a-978a-222de10d13df)

**Comment by Basti-RX** [comment]
Hi. Ich habe jetzt schon einige Pdf's durch was Modbus bei Huawei angeht, aber die Adressen kenne ich nicht. Hast du eine Quelle dafür?

**Comment by Peguschwein** [comment]
![grafik](https://github.com/daolis/ioBroker.sun2000-modbus/assets/160536434/299b12e5-6b40-43f8-a3ab-fa13db0b66cc)

![grafik](https://github.com/daolis/ioBroker.sun2000-modbus/assets/160536434/300e30ba-51ab-4797-bd19-e19c24523903)

kommt aus dem Modbus interface Definitions  Issue 4 vom 29.3.22 Gibt unterdessen ein neueres Dokument aber die Adressen sind sicher noch die gleichen

**Comment by Basti-RX** [comment]
Kannst du die im gesamten hochladen?

**Comment by Peguschwein** [comment]
[Solar Inverter Modbus Interface Definitions 5.pdf](https://github.com/daolis/ioBroker.sun2000-modbus/files/14336439/Solar.Inverter.Modbus.Interface.Definitions.5.pdf)

Hier das gesammte Dokument. Habe da so einiges gesammelt da ich über 1 Monat mit dem Huawei Support dran war

**Comment by Basti-RX** [comment]
Danke. Ist eine neuere Version als die ich kenne. Lese mir die mal durch und dann gucken wir mal was @daolis dazu meint.

**Comment by Basti-RX** [comment]
Wallbox ist bei mir leider nicht vorhanden . Ansonsten sind WR und Batterie gleich.

**Comment by Basti-RX** [comment]
@Peguschwein guckt dir den adapter an. scheint gleich zu sein aber besser weiter entwickelt. kann man auch schon offiziell wohl im iobroker beziehen ohne git

**Comment by Peguschwein** [comment]
@Basti-RX ja habe es soeben installiert sieht gut aus. Grr.... habe ich vergebens ein Bloxkly für die Stringleistung gemacht. Ist ja auch schon bereits drin. Wenn ich noch einen Wunsch anbringen darf String auf 6 odre 8 erhöhen. Mein Kollege hat 42kwp auf dem Dach da reichen 2 Strings nicht mehr :-)

**Comment by Peguschwein** [comment]
Ich denke man sollte die offizielle ModbusAdresse imNamen drin haben. Bei soviel Infospunkte verliert ma schnell den Überblick. z.B 37780_Total _Charge. Ichb bi die neuen Datenpunkte am zuteilen und habe da so meine Mühe dn richtigen zu finden. In der Modbusdefinition ist schön nach Gerät, Adresse und Name. Würe das so übernehmen.

**Comment by daolis** [comment]
> Danke. Ist eine neuere Version als die ich kenne. Lese mir die mal durch und dann gucken wir mal was @daolis dazu meint.

Habe auch den Support kontaktiert, umd die neueste Version zu erhalten. Habe leider auf der Huawei Seite nichts gefunden....
Mal sehen was ich da bekomme! :wink: 

Aber danke fürs hockladen der 5er Version, die kannte ich noch nicht...

**Comment by daolis** [comment]
> Ich denke man sollte die offizielle ModbusAdresse imNamen drin haben. Bei soviel Infospunkte verliert ma schnell den Überblick. z.B 37780_Total _Charge. Ichb bi die neuen Datenpunkte am zuteilen und habe da so meine Mühe dn richtigen zu finden. In der Modbusdefinition ist schön nach Gerät, Adresse und Name. Würe das so übernehmen.

Gute Idee, was haltet ihr davon es in die Description zu schreiben? (siehen Screenshot)

![image](https://github.com/daolis/ioBroker.sun2000-modbus/assets/2550938/95ff00ad-e492-4c6e-ac23-6a82088b0fdb)

**Comment by sansonifabio** [comment]
@daolis ...finde ich gut.

**Comment by daolis** [comment]
most of them in version 0.1.0
