### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.0.2

### ISSUE THREAD

**Issue by GermanBluefox** [daolis/ioBroker.sun2000-modbus#35]
# Think about adding version 0.0.2 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.0.2** (30 days old)
**Installs**: stable=**0** (0%), latest=**86** (49.71%), total=**173**

Click to use [developer portal](https://www.iobroker.dev/adapter/sun2000-modbus/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

Note: This is an automatically generated message and not personally authored by bluefox!
      Do not close this issue manually as a new issue will be created if condition for update still exists
      @mcm1957 for evidence

**Comment by daolis** [comment]
Created PR
https://github.com/ioBroker/ioBroker.repositories/pull/3290

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.0.2 but the current stable version is already 0.0.2.

So this issue should be closed.

@mcm1957 for evidence
