### ISSUE TITLE
Active Power Einheiten nicht durchgängig

### ISSUE THREAD

**Issue by christi-ko** [daolis/ioBroker.sun2000-modbus#8]
**Describe the bug**  
Bei den States für Active Power und Input Power werden unterschiedliche Einheiten verwendet. Teilweise W und teilweise kW. 

**To Reproduce**  
-

**Expected behavior**  
Alle Active Power Werte und Input Power als W angeben. Um das Einheiten durcheinander klein zu halten. Alle Angaben beim Verbrauch in Standard Einheit kWh belassen.

**Screenshots & Logfiles**  
![image](https://github.com/daolis/ioBroker.sun2000-modbus/assets/73897979/5d08327d-9c31-4bf7-9d88-763197c4194f)

**Versions:**  
 - Version 0.0.1 vom Datum 28.08.2023

**Additional context**  
-

**Comment by daolis** [comment]
Hab die Einheiten direkt aus Modbus Interface Definition.
https://javierin.com/wp-content/uploads/sites/2/2021/09/Solar-Inverter-Modbus-Interface-Definitions.pdf

Im FusionSolar Portal werden aber alle in kW angegeben... Sollte wie vermutlich hier auch verwenden... Dann war es nur mehr eine...

**Comment by christi-ko** [comment]
In meinem jetzigen NodeRed [https://forum.iobroker.net/topic/51639/howto-huawei-sun2000-wr-modbus-mit-node-red-read-write](https://forum.iobroker.net/topic/51639/howto-huawei-sun2000-wr-modbus-mit-node-red-read-write) und im Energiefluss-Erweitert habe ich gerade Watt,  weill ja die Zahlen nicht so riesig sind. Die letzten Tage meist unter 1kW 😉.

**Comment by daolis** [comment]
@christi-ko Was meinst du mit 'habe ich gerade Watt, weil ja die Zahlen nicht so riesig sind.' ?

Ich hoffe nicht dass sich die Einheit auf Watt ändert wenn der wert unter 1000 ist, oder?

Wie oben erwähnt verwende ich die Einheiten aus der Modbus Interface definition.
Wenn wer andere Vorschläge hat, nur her damit.
Wir sollten uns aber asap auf units festlegen, im nachhinein ändern ist dann eher ungünstig.
Wenn scripts erstellt und da werte vergleicht, wir das nach unit änderungen eher nicht mehr so toll funktionieren. ;-)

**Comment by daolis** [comment]
Ahh, jetzt hab ich es. Bin wohl anscheinend auf der DC Leitung gestanden ;-)
Also hättest du gerne überall Watt. (Statt kW)

**Comment by christi-ko** [comment]
Genau Watt bei der Power und kWh beim den Energiemengen :-) ...
